public class HeaderWriterTests
{
    [Fact]
    public Task DefaultHeader() =>
        Verify(HeaderWriter.DefaultHeader)
            .NotInline();

    [Fact]
    public Task WriteHeaderDefaultHeader() =>
        Verify(HeaderWriter.WriteHeader("thePath", null, "\r\n"))
            .Snapshot(
                """
                <!--
                GENERATED FILE - DO NOT EDIT
                This file was generated by [MarkdownSnippets](https://github.com/SimonCropp/MarkdownSnippets).
                Source File: thePath
                To change this file edit the source file and then run MarkdownSnippets.
                -->

                """);

    [Fact]
    public Task WriteHeaderHeaderCustom() =>
        Verify(HeaderWriter.WriteHeader("thePath", @"line1\nline2", "\r\n"))
            .Snapshot(
                """
                <!--
                line1
                line2
                -->

                """);
}