using System.IO;

static class HeaderWriter
{
    public static void WriteHeader(string sourceFile, string rootDirectory, TextWriter writer)
    {
        var relativeSource = sourceFile
            .ReplaceCaseless(rootDirectory, "")
            .Replace('\\', '/');
        writer.WriteLine(@"<!--");
        writer.WriteLine(@"This file was generated by MarkdownSnippets from source file {relativeSource}.");
        writer.WriteLine($@"");
        writer.WriteLine(@"To change this file edit the source file and then re-run the generation using either the [dotnet global tool](https://github.com/SimonCropp/MarkdownSnippets#markdownsnippetstool) or using the [api](https://github.com/SimonCropp/MarkdownSnippets#running-as-a-unit-test).");
        writer.WriteLine(@"-->");
    }
}
