
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Argon" />
    <PackageReference Include="ProjectFiles" />
    <PackageReference Include="Verify.DiffPlex" />
    <PackageReference Include="Verify.TUnit" />
    <PackageReference Include="DiffEngine" />
    <PackageReference Include="EmptyFiles" />
    <PackageReference Include="SimpleInfoName" />
    <PackageReference Include="Verify" />
    <PackageReference Include="TUnit" />
    <ProjectReference Include="..\MarkdownSnippets.Tool\MarkdownSnippets.Tool.csproj" />
    <ProjectReference Include="..\MarkdownSnippets\MarkdownSnippets.csproj" />
    <PackageReference Include="ProjectDefaults" PrivateAssets="all" />
  </ItemGroup>
</Project>
