<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>testing</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ConfigReader\ConfigReader.csproj" />
    <PackageReference Include="ProjectFiles" />
    <PackageReference Include="Verify.DiffPlex" />
    <PackageReference Include="Verify.TUnit" />
    <PackageReference Include="Argon" />
    <PackageReference Include="DiffEngine" />
    <PackageReference Include="EmptyFiles" />
    <PackageReference Include="SimpleInfoName" />
    <PackageReference Include="Verify" />
    <PackageReference Include="TUnit" />
    <PackageReference Include="ProjectDefaults" PrivateAssets="all" />
    <None Update="allConfig.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="SourceTransform.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>

    <None Update="InPlaceOverwrite.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
